/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\terrain-complete.glb -o src/components/level/terrain/complete.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/terrain-complete.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rock.geometry} material={nodes.rock.material} position={[46.01, 0.235, -122.409]} rotation={[-Math.PI, 1.084, -Math.PI]} scale={[4.051, 2.792, 6.206]} />
      <mesh geometry={nodes.rock001.geometry} material={nodes.rock001.material} position={[110.941, 0.57, -82.805]} rotation={[Math.PI, -0.019, Math.PI]} scale={[4.051, 3.848, 6.206]} />
      <mesh geometry={nodes.rock002.geometry} material={nodes.rock002.material} position={[49.724, 1.906, -108.366]} rotation={[2.994, -0.101, -2.906]} scale={[4.051, 3.848, 6.206]} />
      <mesh geometry={nodes.rock003.geometry} material={nodes.rock003.material} position={[65.065, 2.367, -94.905]} rotation={[2.991, -0.696, -3.076]} scale={[4.051, 3.848, 6.206]} />
      <mesh geometry={nodes.rock004.geometry} material={nodes.rock004.material} position={[64.848, 8.136, -80.148]} rotation={[-3.137, -0.018, -2.915]} scale={[3.977, 2.159, 6.206]} />
      <mesh geometry={nodes.rock005.geometry} material={nodes.rock005.material} position={[115.114, 3.514, -66.049]} rotation={[2.988, -0.018, -2.915]} scale={[3.977, 2.159, 6.206]} />
      <mesh geometry={nodes.rock006.geometry} material={nodes.rock006.material} position={[76.283, 5.23, -71.895]} rotation={[-3.135, -0.017, -2.78]} scale={[4.051, 3.848, 6.206]} />
      <mesh geometry={nodes.rock007.geometry} material={nodes.rock007.material} position={[19, -0.201, 42.498]} rotation={[Math.PI, -0.019, Math.PI]} scale={[3.937, 3.739, 6.031]} />
      <mesh geometry={nodes.rock008.geometry} material={nodes.rock008.material} position={[79.778, 5.659, 64.8]} rotation={[Math.PI, -0.019, Math.PI]} scale={[3.937, 3.739, 6.031]} />
      <mesh geometry={nodes.rock009.geometry} material={nodes.rock009.material} position={[108.44, 5.3, 31.763]} rotation={[2.951, -1.457, 3.114]} scale={[8.114, 2.851, 5.998]} />
      <mesh geometry={nodes.rock010.geometry} material={nodes.rock010.material} position={[99.91, 5.357, 87.706]} rotation={[0.133, 0.097, -0.271]} scale={[4.073, 5.296, 6.089]} />
      <mesh geometry={nodes.rock011.geometry} material={nodes.rock011.material} position={[-37.627, 12.118, -79.762]} rotation={[0, 0.417, 0]} scale={[3.937, 7.419, 6.031]} />
      <mesh geometry={nodes.rock012.geometry} material={nodes.rock012.material} position={[-52.38, 25.216, -59.235]} rotation={[0.144, 0.464, -0.362]} scale={[4.019, 1.822, 6.056]} />
      <mesh geometry={nodes.rock013.geometry} material={nodes.rock013.material} position={[30.178, -0.201, -60.025]} rotation={[Math.PI, -1.051, Math.PI]} scale={[3.194, 3.034, 4.893]} />
      <mesh geometry={nodes.rock014.geometry} material={nodes.rock014.material} position={[-70.445, 8.026, 17.754]} rotation={[0, -0.543, 0]} scale={[3.937, 3.739, 6.031]} />
      <mesh geometry={nodes.rock015.geometry} material={nodes.rock015.material} position={[135.876, -1.271, -133.791]} rotation={[-Math.PI, 1.16, -Math.PI]} scale={[4.051, 3.848, 6.206]} />
      <mesh geometry={nodes.trunk.geometry} material={materials['trunk.001']} position={[107.167, 10.052, -38.291]} scale={1.411} />
      <mesh geometry={nodes.trunk001.geometry} material={materials['trunk.001']} position={[99.447, 10.138, -38.868]} rotation={[0, 0.147, 0]} scale={1.09} />
      <mesh geometry={nodes.trunk002.geometry} material={materials['trunk.001']} position={[108.497, 10.339, -29.436]} rotation={[0, -0.484, 0]} scale={1.09} />
      <mesh geometry={nodes.trunk003.geometry} material={materials['trunk.001']} position={[66.187, 6.015, -33.011]} rotation={[0, -0.109, 0]} scale={1.023} />
      <mesh geometry={nodes.trunk004.geometry} material={materials['trunk.001']} position={[103.421, 4.98, 22.828]} rotation={[0, 0.013, 0]} scale={1.145} />
      <mesh geometry={nodes.trunk005.geometry} material={materials['trunk.001']} position={[72.772, 7.528, -27.595]} rotation={[0, -0.913, 0]} scale={0.924} />
      <mesh geometry={nodes.trunk006.geometry} material={materials['trunk.001']} position={[102.794, 10.467, -23.899]} rotation={[0, 0.807, 0]} scale={1.09} />
      <mesh geometry={nodes.trunk007.geometry} material={materials['trunk.001']} position={[105.404, 9.989, -18.097]} rotation={[0, 0.603, 0]} scale={1.09} />
      <mesh geometry={nodes.trunk008.geometry} material={materials['trunk.001']} position={[103.248, 9.417, -9.326]} rotation={[-Math.PI, 1.172, -Math.PI]} scale={1.09} />
      <mesh geometry={nodes.trunk009.geometry} material={materials['trunk.001']} position={[59.729, 4.023, -15.721]} rotation={[0, -1.236, 0]} scale={0.924} />
      <mesh geometry={nodes.trunk010.geometry} material={materials['trunk.001']} position={[116.607, 3.215, -122.998]} rotation={[0, 0.147, 0]} scale={1.09} />
      <mesh geometry={nodes.trunk011.geometry} material={materials['trunk.001']} position={[98.395, 3.551, 16.192]} rotation={[Math.PI, -1.507, Math.PI]} scale={1.145} />
      <mesh geometry={nodes.trunk012.geometry} material={materials['trunk.001']} position={[-55.657, 26.324, -52.576]} rotation={[0, -0.484, 0]} scale={1.788} />
      <mesh geometry={nodes.trunk013.geometry} material={materials['trunk.001']} position={[-68.945, 28.201, -51.641]} rotation={[0, -1.236, 0]} scale={1.173} />
      <mesh geometry={nodes.trunk014.geometry} material={materials['trunk.001']} position={[-66.265, 28.095, -61.007]} rotation={[-Math.PI, 0.741, -Math.PI]} scale={1.173} />
      <mesh geometry={nodes.trunk015.geometry} material={materials['trunk.001']} position={[-92.528, 9.535, 10.789]} rotation={[0, -0.484, 0]} scale={1.788} />
      <mesh geometry={nodes.trunk016.geometry} material={materials['trunk.001']} position={[-82.999, 7.993, 20.352]} rotation={[0, 1.518, 0]} scale={1.788} />
      <mesh geometry={nodes.trunk017.geometry} material={materials['trunk.001']} position={[-99.895, 5.232, 29.884]} rotation={[0, 1.518, 0]} scale={2.333} />
      <mesh geometry={nodes.trunk018.geometry} material={materials['trunk.001']} position={[-107.008, 4.262, 35.678]} rotation={[-Math.PI, 0.686, -Math.PI]} scale={1.488} />
      <mesh geometry={nodes.trunk019.geometry} material={materials['trunk.001']} position={[-99.034, 4.909, 45.83]} rotation={[-Math.PI, 1.172, -Math.PI]} scale={1.488} />
      <mesh geometry={nodes.trunk020.geometry} material={materials['trunk.001']} position={[76.049, 6.603, 86.487]} rotation={[0, 0.013, 0]} scale={1.145} />
      <mesh geometry={nodes.trunk021.geometry} material={materials['trunk.001']} position={[86.735, 4.521, 101.177]} rotation={[0, 0.539, 0]} scale={1.145} />
      <mesh geometry={nodes.trunk022.geometry} material={materials['trunk.001']} position={[-103.871, 6.383, 15.3]} rotation={[-Math.PI, 1.172, -Math.PI]} scale={1.488} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/terrain-complete.glb')
