/* eslint-disable react-hooks/exhaustive-deps */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Maria.gltf -o src/components/Player/Maria.jsx 
*/

import { useEffect, useRef, useMemo } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useStore } from "../../hooks/useStore";
import { MeshStandardMaterial } from "three";

export function Maria(props) {
  const group = useRef();
  const { scene, animations } = useGLTF("/models/Maria.gltf");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  const customMaterial = new MeshStandardMaterial({
    map: materials.m_char.map,
  });

  const characterState = useStore((state) => state.characterState);

  useEffect(() => {
    actions[characterState].reset().fadeIn(0.3).play();

    return () => {
      actions[characterState].fadeOut(0.3);
    };
  }, [characterState]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Body"
            geometry={nodes.Body.geometry}
            // material={materials.m_char}
            material={customMaterial}
            skeleton={nodes.Body.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Maria.gltf");
